### PR TITLE
GH-3910 Initialize MemValueFactory with common vocabulary

### PR DESCRIPTION
**Pull request by hmottestad**
GitHub issue resolved: #3910 

Briefly describe the changes proposed in this PR:

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) for more details):

 - [ ] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [ ] I've added tests for the changes I made
 - [ ] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [ ] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [ ] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by hmottestad** [comment]
## Before
```
Benchmark                                 Mode  Cnt    Score   Error  Units
GetStatementsBenchmark.getTypesAndLabels  avgt    5  138.205 ± 3.405  ms/op
GetStatementsBenchmark.groupByLanguage    avgt    5    0.395 ± 0.035  ms/op
GetStatementsBenchmark.groupByType        avgt    5    5.550 ± 1.104  ms/op
```

## After
```

```

**Comment by hmottestad** [comment]
At the moment I haven't found any existing benchmarks that are improved in this branch. The changes are based on my WIP performance branch #3854. Fixing one bottle neck will often reveal another performance issue that was masked by the initial bottle neck, so that might be the case here too. That being said there are quite a few fixes in that branch that didn't end up making much of a difference.

**Comment by hmottestad** [comment]
## Before
```
```

## After
```
Benchmark                                                              (param)  Mode  Cnt   Score   Error  Units
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencer  moreRdfs::12180  avgt    5  10.517 ± 0.882  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencer  longChain::5803  avgt    5   7.472 ± 0.511  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencer      medium::544  avgt    5   0.800 ± 0.085  ms/op
ReasoningBenchmark.forwardChainingSchemaCachingRDFSInferencer      simple::152  avgt    5   0.436 ± 0.033  ms/op
```

**Comment by jeenbroekstra** [comment]
Marking as stale to indicate this has been inactive for a while, and we should consider closing it.

**Pull request closed without merging**
