### PR TITLE
GH-4401 switch to new config vocabulary as the default

### PR DESCRIPTION
**Pull request by abrokenjester**
GitHub issue resolved: #4401 

Briefly describe the changes proposed in this PR:

- remove experimental status of CONFIG vocabulary
- switch back to use of new vocabulary as the default (using legacy vocab as a fallback) 
- added support for fully converting existing config files
- added test coverage for working with legacy config files
- added an env var feature flag to optionally switch back to legacy vocabulary.
- added release/upgrade notes

----
PR Author Checklist (see the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md) for more details):

 - [x] my pull request is [self-contained](https://rdf4j.org/documentation/developer/merge-strategy/#self-contained-changes-pull-requests-and-commits)
 - [x] I've added tests for the changes I made
 - [x] I've applied [code formatting](https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md#code-formatting) (you can use `mvn process-resources` to format from the command line)
 - [x] I've [squashed](https://rdf4j.org/documentation/developer/squashing) my commits where necessary 
 - [x] every commit message starts with the issue number (GH-xxxx) followed by a meaningful description of the change

### CODE REVIEW

**Comment by abrokenjester** [comment]
@hmottestad I'm getting a build failure in the osgi-runtime - I seem to recall you recently had a similar issue?

**Comment by abrokenjester** [comment]
Looks like there was a fix for the osgi issue on main which is not yet synced onto the develop branch. Doing a manual branch sync.

**Comment by abrokenjester** [comment]
Doing a small fix in the package-assembly github action - see https://github.com/eclipse-rdf4j/rdf4j/pull/4746

**Comment by hmottestad** [comment]
I'm having a bit of second thoughts about changing up the vocabulary. I know that we don't own the domain names anymore, but that doesn't really affect our code. 

I had put some effort into making the new and old vocabulary work together in 4.3, but it still managed to break the sail templates used in the workbench. And we don't have a single test for the workbench as far as I can tell. It's a bit worrying that we will have to do a lot of manual verification and hope we've thought of everything. And that also goes for everyone building on top of RDF4J, for instance GraphDB and Halyard.

**Comment by abrokenjester** [comment]
I'm planning to run some further manual tests and report those here. I've also,  as part of this PR, significantly improved test coverage and added better support for mixed vocab usage as well as the choice to stick completely with legacy vocab for now (though I don't recommend that). 

Workbench test coverage is a problem,  but not to the extent that I want to cancel this improvement.  The breakage in 4.3 was unfortunate but those problems have been addressed,  and this time we are doing this as part of a major release.

**Comment by abrokenjester** [comment]
# Test Notes

## default behavior

- [ ] Server and Workbench start correctly
- [ ] new repository gets created with new vocabulary config and is usable 
- [ ] legacy config gets read correctly and converted

## useLegacyConfig flag enabled

- [ ]  Server and Workbench start correctly
- [ ] new repository gets created with legacy vocabulary config and is usable 
- [ ] legacy config gets read correctly and is _not_ converted

**Comment by abrokenjester** [comment]
Given the above and the test results I shared, could I get another review over this? If there's additional things you'd like to see tested (but don't have the time to do yourself) let me know and I can take a look at it over the weekend. If not, I would consider this done and we can merge it into develop.

**Comment by hmottestad** [comment]
I'll try to find some time to look it over again.

**Review by hmottestad — APPROVED** [review]
I tested on my laptop a bit and didn't manage to break anything.

**Pull request merged**
